// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.2.1-IE
// Author: meta-egg
// Generated at: 2023-05-08 00:14

package repo

import (
	"github.com/google/wire"
	// mock "meta-egg-layout/internal/repo/mock"
)

// ProviderSet is repo providers.
var ProviderSet = wire.NewSet(
	NewUserRepo,
	NewGenderRepo,
)

// MockProviderSet is mock repo providers.
var MockProviderSet = wire.NewSet(
// mock.NewMockUserRepo,
// wire.Bind(new(UserRepo), new(*mock.MockUserRepo)),
)
