// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.2.1-IE
// Author: meta-egg
// Generated at: 2023-05-08 00:14

package repo

import (
	gen "meta-egg-layout/gen/repo"
	"meta-egg-layout/internal/common/resource"
)

//go:generate mockgen -package mock -destination ./mock/gender.go . GenderRepo
type GenderRepo interface {
	gen.GenderRepo

	// your repo interface here
	// xxx(xxx) xxx
}

type GenderRepoImpl struct {
	gen.GenderRepoImpl
}

func NewGenderRepo(rsrc *resource.Resource) GenderRepo {
	return &GenderRepoImpl{
		GenderRepoImpl: gen.GenderRepoImpl{
			Resource: rsrc,
		},
	}
}

// your repo implement here
// func (r *GenderRepoImpl) Xxx (xxx) (xxx) {}
