/*
 * Generated by meta-egg.
 * WILL NOT be replace after re-generated. CAREFULLY EDIT.
 * Version: v0.9.0-96bf0e0
 * Author: meta-egg
 * Generated at: 2023-04-13 09:27
 */
package repo

import (
	gen "meta-egg-layout/gen/repo"
	"meta-egg-layout/internal/common/resource"
)

//go:generate mockgen -package mock -destination ./mock/gender.go . GenderRepo
type GenderRepo interface {
	gen.GenderRepo

	// your repo interface here
	// func xxx(xxx) xxx
}

type GenderRepoImpl struct {
	gen.GenderRepoImpl
}

func NewGenderRepo(rsrc *resource.Resource) GenderRepo {
	return &GenderRepoImpl{
		GenderRepoImpl: gen.GenderRepoImpl{
			Resource: rsrc,
		},
	}
}

// your repo implement here
// func (r *GenderRepo) Xxx (xxx) (xxx) {}
