// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.8.0
// Author: meta-egg
// Generated at: 2025-08-24 21:54

package repo

import (
	"context"
	"meta-egg-layout/gen/model"
	gen "meta-egg-layout/gen/repo"
	"meta-egg-layout/internal/common/contexts"
	"meta-egg-layout/internal/common/resource"
	"meta-egg-layout/internal/repo/option"
	"meta-egg-layout/pkg/gormx"

	jgstr "github.com/Jinglever/go-string"
)

//go:generate mockgen -package mock -destination ./mock/tag.go . TagRepo
type TagRepo interface {
	gen.TagRepo

	GetList(ctx context.Context, opt *option.TagListOption) ([]*model.Tag, int64, error)
}

type TagRepoImpl struct {
	gen.TagRepoImpl
}

func NewTagRepo(rsrc *resource.Resource) TagRepo {
	return &TagRepoImpl{
		TagRepoImpl: gen.TagRepoImpl{
			Resource: rsrc,
		},
	}
}

func (r *TagRepoImpl) GetList(ctx context.Context, opt *option.TagListOption) ([]*model.Tag, int64, error) {
	log := contexts.GetLogger(ctx).
		WithField("opt", jgstr.JsonEncode(opt))
	ops := make([]gormx.Option, 0)
	if opt != nil && opt.Filter != nil {
		ops = append(ops, opt.Filter.GetRepoOptions()...)
	}
	if opt != nil && opt.Order != nil {
		validOrderby := []string{
			model.ColTagID,
		}
		ops = append(ops, opt.Order.GetRepoOptions(validOrderby)...)
	}
	total, err := r.Count(ctx, ops...)
	if err != nil {
		log.WithError(err).Error("fail to count tag list")
		return nil, 0, err
	}
	if total == 0 {
		return make([]*model.Tag, 0), 0, nil
	}
	if opt != nil && opt.Pagination != nil {
		ops = append(ops, opt.Pagination.GetRepoOptions()...)
	}
	if opt != nil && len(opt.Select) > 0 {
		ops = append(ops, gormx.Select(opt.Select...))
	}
	ms, err := r.Gets(ctx, ops...)
	if err != nil {
		log.WithError(err).Error("fail to get tag list")
		return nil, 0, err
	}
	return ms, total, nil
}
