// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.0.0-EE
// Author: meta-egg
// Generated at: 2023-04-16 18:27
package repo

import (
	gen "meta-egg-layout/gen/repo"
	"meta-egg-layout/internal/common/resource"
)

//go:generate mockgen -package mock -destination ./mock/user.go . UserRepo
type UserRepo interface {
	gen.UserRepo

	// your repo interface here
	// func xxx(xxx) xxx
}

type UserRepoImpl struct {
	gen.UserRepoImpl
}

func NewUserRepo(rsrc *resource.Resource) UserRepo {
	return &UserRepoImpl{
		UserRepoImpl: gen.UserRepoImpl{
			Resource: rsrc,
		},
	}
}

// your repo implement here
// func (r *UserRepo) Xxx (xxx) (xxx) {}
