// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package integrate

import (
	"meta-egg-layout/internal/biz"
	"meta-egg-layout/internal/common/resource"
	"meta-egg-layout/internal/repo"
)

// Injectors from wire.go:

func NewBizService(rsrc *resource.Resource) *biz.BizService {
	userRepo := repo.NewUserRepo(rsrc)
	genderRepo := repo.NewGenderRepo(rsrc)
	bizService := biz.NewBizService(rsrc, userRepo, genderRepo)
	return bizService
}
