// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.2.0-IE
// Author: meta-egg
// Generated at: 2024-01-01 22:48

package server

import (
	hdl "meta-egg-layout/internal/handler/http"

	"github.com/gin-gonic/gin"
)

// annotation for swagger
// @title	meta-egg-layout
// @version xxx
func (s *Server) initRouter() {
	router := gin.New()
	router.Use(Logger(), gin.Recovery())
	router.Use(errorHandler(s.Cfg))
	apiGroup := router.Group("/api/v1")
	// skip authHandler for some path
	skipFullPath := map[string]struct{}{}
	apiGroup.Use(authHandler(s.Resource.AccessToken, s.Cfg, skipFullPath))

	handler := hdl.WireHandler(s.Resource)

	// 用户
	apiGroup.POST("/users", handler.CreateUser)
	apiGroup.GET("/users/:id", handler.GetUserDetail)
	apiGroup.GET("/users", handler.GetUserList)
	apiGroup.PUT("/users/:id", handler.UpdateUser)
	apiGroup.DELETE("/users/:id", handler.DeleteUser)

	s.Router = router
}
