// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.8.0
// Author: meta-egg
// Generated at: 2025-08-24 22:42

package server

import (
	hdl "meta-egg-layout/internal/handler/http"

	"github.com/gin-gonic/gin"
)

// annotation for swagger
// @title	meta-egg-layout
// @version xxx
func (s *Server) initRouter() {
	router := gin.New()
	router.Use(Logger(), gin.Recovery())
	router.Use(errorHandler(s.Cfg))
	apiGroup := router.Group("/api/v1")
	// skip authHandler for some path
	skipFullPath := map[string]struct{}{}
	apiGroup.Use(authHandler(s.Resource.AccessToken, s.Cfg, skipFullPath))

	handler := hdl.WireHandler(s.Resource)

	// 用户
	apiGroup.POST("/users", handler.CreateUser)
	apiGroup.GET("/users/:id", handler.GetUserDetail)
	apiGroup.GET("/users", handler.GetUserList)
	apiGroup.PUT("/users/:id", handler.UpdateUser)
	apiGroup.DELETE("/users/:id", handler.DeleteUser)
	// 用户用户电话
	apiGroup.POST("/users/:user_id/user_phones", handler.AddUserPhone)
	apiGroup.DELETE("/users/:user_id/user_phones/:user_phone_id", handler.RemoveUserPhone)
	apiGroup.GET("/users/:user_id/user_phones", handler.GetAllUserPhone)

	// 用户标签关系
	apiGroup.GET("/users/{user_id}/tags", handler.GetTagListByUserID)
	apiGroup.GET("/tags/{tag_id}/users", handler.GetUserListByTagID)
	apiGroup.POST("/users/{user_id}/bind-tags", handler.BindTagsToUser)
	apiGroup.POST("/tags/{tag_id}/bind-users", handler.BindUsersToTag)
	apiGroup.POST("/users/{user_id}/unbind-tags", handler.UnbindTagsFromUser)
	apiGroup.POST("/tags/{tag_id}/unbind-users", handler.UnbindUsersFromTag)
	// 标签
	apiGroup.POST("/tags", handler.CreateTag)
	apiGroup.GET("/tags/:id", handler.GetTagDetail)
	apiGroup.GET("/tags", handler.GetTagList)
	apiGroup.PUT("/tags/:id", handler.UpdateTag)
	apiGroup.DELETE("/tags/:id", handler.DeleteTag)

	s.Router = router
}
