// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.1.0-EE
// Author: meta-egg
// Generated at: 2023-04-27 19:17

package server

import (
	"github.com/gin-gonic/gin"
)

// annotation for swagger
// @title	meta-egg-layout
// @version xxx
func (s *Server) initRouter() {
	router := gin.Default()
	router.Use(errorHandler())
	authGroup := router.Group("/v1")
	authGroup.Use(authHandler(s.Resource.JWT, s.Cfg))

	handler := NewHandler(s.Resource)

	// 用户
	authGroup.POST("/users", handler.CreateUser)
	authGroup.GET("/users/:id", handler.GetUserDetail)
	authGroup.GET("/users", handler.GetUserList)
	authGroup.PUT("/users/:id", handler.UpdateUser)

	s.Router = router
}
