// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"meta-egg-layout/internal/biz"
	"meta-egg-layout/internal/common/resource"
	"meta-egg-layout/internal/handler/grpc"
	"meta-egg-layout/internal/repo"
)

// Injectors from wire.go:

func NewHandler(rsrc *resource.Resource) *handler.Handler {
	userRepo := repo.NewUserRepo(rsrc)
	genderRepo := repo.NewGenderRepo(rsrc)
	bizService := biz.NewBizService(rsrc, userRepo, genderRepo)
	handlerHandler := handler.NewHandler(rsrc, bizService)
	return handlerHandler
}
