// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.1.5-EE
// Author: meta-egg
// Generated at: 2023-05-01 17:18

package constraint

const (
	// 日期格式
	DateFormat = "2006-01-02"
	// 分钟级时间格式
	MinuteTimeFormat = "2006-01-02 15:04"
	// 秒级时间格式
	SecondTimeFormat = "2006-01-02 15:04:05"
	// 时分格式
	HourMinuteFormat = "15:04"
	// 时分秒格式
	HourMinuteSecondFormat = "15:04:05"
)
