// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.0.0-EE
// Author: meta-egg
// Generated at: 2023-04-16 18:27
package main

import (
	"flag"
	"os"
	"os/signal"
	"syscall"

	"meta-egg-layout/internal/common/resource"
	"meta-egg-layout/internal/config"
	grpcserver "meta-egg-layout/internal/server/grpc"
	httpserver "meta-egg-layout/internal/server/http"
	"meta-egg-layout/pkg/version"

	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
)

var (
	configFilePath = flag.String("config", "./configs/conf.yaml", "config file")
)

func main() {
	flag.Parse()
	if *version.PrintVersion {
		version.Printer()
		return
	}

	logrus.SetLevel(logrus.InfoLevel)
	logrus.SetReportCaller(true)
	logrus.SetFormatter(&logrus.TextFormatter{
		DisableQuote:    true,
		TimestampFormat: "2006-01-02 15:04:05",
	})

	// load config
	if err := config.LoadConfig(*configFilePath); err != nil {
		logrus.Fatalf("load config error %v", err)
	}

	// init resource
	rsrc, rsrcCancel, err := resource.InitResource(config.GetResourceConfig())
	if err != nil {
		logrus.Fatalf("init resource error %v", err)
	}

	// run http server
	gin.SetMode(gin.ReleaseMode)
	httpCancel := httpserver.NewServer(config.GetHTTPServerConfig(), rsrc).Run()

	// run grpc server
	grpcCancel := grpcserver.NewServer(config.GetGRPCServerConfig(), rsrc).Run()

	sc := make(chan os.Signal, 1)
	signal.Notify(sc, os.Interrupt, syscall.SIGTERM)
	<-sc

	httpCancel()
	grpcCancel()
	rsrcCancel()
	logrus.Info("meta-egg-layout exit")
}
