/*
 * Generated by meta-egg.
 * WILL NOT be replace after re-generated. CAREFULLY EDIT.
 * Version: master-046024d-dirty
 * Author: meta-egg
 * Generated at: 2023-04-12 13:10
 */
package contexts

import (
	"context"
	"encoding/json"

	"github.com/sirupsen/logrus"
)

type KeyME struct{}

type ME struct {
	ID uint64 `json:"id"` // ID of the user
}

func (me *ME) MustToJSON() string {
	s, err := json.Marshal(me)
	if err != nil {
		logrus.Fatalf("ME.ToJSON Err: %v", err)
	}
	return string(s)
}

func SetME(ctx context.Context, me ME) context.Context {
	return context.WithValue(ctx, KeyME{}, me)
}

func GetME(ctx context.Context) (ME, bool) {
	me, ok := ctx.Value(KeyME{}).(ME)
	return me, ok
}

func DelME(ctx context.Context) context.Context {
	return context.WithValue(ctx, KeyME{}, nil)
}
