// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.7.0-IE
// Author: meta-egg
// Generated at: 2023-08-24 02:30

package gormx

import "time"

func CorrectTimezone(t time.Time) time.Time {
	return time.Date(t.Year(),
		t.Month(),
		t.Day(),
		t.Hour(),
		t.Minute(),
		t.Second(),
		t.Nanosecond(), time.Local)
}
