// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.4.1-IE
// Author: meta-egg
// Generated at: 2023-05-18 18:05

package gormx

import (
	"context"

	"gorm.io/gorm"
)

type CtxKeyTX struct{}

func setTX(ctx context.Context, tx *gorm.DB) context.Context {
	return context.WithValue(ctx, CtxKeyTX{}, tx)
}

func getTX(ctx context.Context) (*gorm.DB, bool) {
	tx, ok := ctx.Value(CtxKeyTX{}).(*gorm.DB)
	return tx, ok
}
