// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.2.5-EE
// Author: meta-egg
// Generated at: 2023-05-10 17:24

package gormx

import (
	"context"

	"gorm.io/gorm"
)

type CtxKeyTX struct{}

func setTX(ctx context.Context, tx *gorm.DB) context.Context {
	return context.WithValue(ctx, CtxKeyTX{}, tx)
}

func getTX(ctx context.Context) (*gorm.DB, bool) {
	tx, ok := ctx.Value(CtxKeyTX{}).(*gorm.DB)
	return tx, ok
}

func GetTX(ctx context.Context, db *gorm.DB) *gorm.DB {
	tx, ok := getTX(ctx)
	if !ok {
		tx = db
	}
	return tx
}

func Begin(ctx context.Context, db *gorm.DB) (context.Context, error) {
	tx := GetTX(ctx, db).Begin()
	if tx.Error != nil {
		return nil, tx.Error
	}
	return setTX(ctx, tx), nil
}

func Commit(ctx context.Context) error {
	tx, ok := getTX(ctx)
	if !ok {
		return nil
	}

	return tx.Commit().Error
}

func Rollback(ctx context.Context) error {
	tx, ok := getTX(ctx)
	if !ok {
		return nil
	}

	return tx.Rollback().Error
}
