// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.2.0-IE
// Author: meta-egg
// Generated at: 2024-01-01 22:48

package option

import (
	"meta-egg-layout/pkg/gormx"
)

type GenderFilterOption struct {
}

func (o *GenderFilterOption) GetRepoOptions() []gormx.Option {
	ops := make([]gormx.Option, 0)
	return ops
}

type GenderListOption struct {
	Pagination *PaginationOption
	Order      *OrderOption
	Filter     *GenderFilterOption
	Select     []interface{} // select columns, such as []interface{}{"id", "name"}
}
