// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.8.0
// Author: meta-egg
// Generated at: 2025-08-24 21:54

package option

import (
	"meta-egg-layout/pkg/gormx"
)

type TagFilterOption struct {
}

func (o *TagFilterOption) GetRepoOptions() []gormx.Option {
	ops := make([]gormx.Option, 0)
	return ops
}

type TagListOption struct {
	Pagination *PaginationOption
	Order      *OrderOption
	Filter     *TagFilterOption
	Select     []interface{} // select columns, such as []interface{}{"id", "name"}
}
