// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.9.0-CE
// Author: meta-egg
// Generated at: 2023-09-12 19:27

package option

import (
	"meta-egg-layout/gen/model"
	"meta-egg-layout/pkg/gormx"
)

type UserFilterOption struct {
	Gender  *uint64 // 性别
	IsOnJob *bool   // 是否在职
}

func (o *UserFilterOption) GetRepoOptions() []gormx.Option {
	ops := make([]gormx.Option, 0)
	if o.Gender != nil {
		ops = append(ops, gormx.Where(model.ColUserGender+" = ?", *o.Gender))
	}
	if o.IsOnJob != nil {
		ops = append(ops, gormx.Where(model.ColUserIsOnJob+" = ?", *o.IsOnJob))
	}
	return ops
}

type UserListOption struct {
	Pagination *PaginationOption
	Order      *OrderOption
	Filter     *UserFilterOption
	Select     []interface{} // select columns, such as []interface{}{"id", "name"}
}
