// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.1.2-IE
// Author: meta-egg
// Generated at: 2023-04-29 11:57

package usecase

import (
	"github.com/google/wire"
)

// ProviderSet is domain providers.
var ProviderSet = wire.NewSet()
