// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.1.0-EE
// Author: meta-egg
// Generated at: 2023-04-27 19:17

package domain

import (
	"github.com/google/wire"
)

// ProviderSet is domain providers.
var ProviderSet = wire.NewSet()
