// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.1
// source: meta_egg_layout.proto

package meta_egg_layout

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaEggLayout_CreateUser_FullMethodName         = "/metaegglayout.MetaEggLayout/CreateUser"
	MetaEggLayout_GetUserDetail_FullMethodName      = "/metaegglayout.MetaEggLayout/GetUserDetail"
	MetaEggLayout_GetUserList_FullMethodName        = "/metaegglayout.MetaEggLayout/GetUserList"
	MetaEggLayout_UpdateUser_FullMethodName         = "/metaegglayout.MetaEggLayout/UpdateUser"
	MetaEggLayout_DeleteUser_FullMethodName         = "/metaegglayout.MetaEggLayout/DeleteUser"
	MetaEggLayout_AddUserPhone_FullMethodName       = "/metaegglayout.MetaEggLayout/AddUserPhone"
	MetaEggLayout_RemoveUserPhone_FullMethodName    = "/metaegglayout.MetaEggLayout/RemoveUserPhone"
	MetaEggLayout_GetAllUserPhone_FullMethodName    = "/metaegglayout.MetaEggLayout/GetAllUserPhone"
	MetaEggLayout_GetTagListByUserID_FullMethodName = "/metaegglayout.MetaEggLayout/GetTagListByUserID"
	MetaEggLayout_GetUserListByTagID_FullMethodName = "/metaegglayout.MetaEggLayout/GetUserListByTagID"
	MetaEggLayout_BindTagsToUser_FullMethodName     = "/metaegglayout.MetaEggLayout/BindTagsToUser"
	MetaEggLayout_BindUsersToTag_FullMethodName     = "/metaegglayout.MetaEggLayout/BindUsersToTag"
	MetaEggLayout_UnbindTagsFromUser_FullMethodName = "/metaegglayout.MetaEggLayout/UnbindTagsFromUser"
	MetaEggLayout_UnbindUsersFromTag_FullMethodName = "/metaegglayout.MetaEggLayout/UnbindUsersFromTag"
	MetaEggLayout_CreateTag_FullMethodName          = "/metaegglayout.MetaEggLayout/CreateTag"
	MetaEggLayout_GetTagDetail_FullMethodName       = "/metaegglayout.MetaEggLayout/GetTagDetail"
	MetaEggLayout_GetTagList_FullMethodName         = "/metaegglayout.MetaEggLayout/GetTagList"
	MetaEggLayout_UpdateTag_FullMethodName          = "/metaegglayout.MetaEggLayout/UpdateTag"
	MetaEggLayout_DeleteTag_FullMethodName          = "/metaegglayout.MetaEggLayout/DeleteTag"
)

// MetaEggLayoutClient is the client API for MetaEggLayout service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaEggLayoutClient interface {
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserDetail, error)
	// 获取用户详情
	GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*UserDetail, error)
	// 获取用户列表
	GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error)
	// 更新用户
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除用户
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 添加用户电话
	AddUserPhone(ctx context.Context, in *AddUserPhoneRequest, opts ...grpc.CallOption) (*UserPhoneDetail, error)
	// 删除用户电话
	RemoveUserPhone(ctx context.Context, in *RemoveUserPhoneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取所有用户电话
	GetAllUserPhone(ctx context.Context, in *GetAllUserPhoneRequest, opts ...grpc.CallOption) (*GetAllUserPhoneResponse, error)
	// 获取与指定用户关联的标签列表
	GetTagListByUserID(ctx context.Context, in *GetTagListByUserIDRequest, opts ...grpc.CallOption) (*GetTagListResponse, error)
	// 获取与指定标签关联的用户列表
	GetUserListByTagID(ctx context.Context, in *GetUserListByTagIDRequest, opts ...grpc.CallOption) (*GetUserListResponse, error)
	// 给指定用户批量关联标签
	BindTagsToUser(ctx context.Context, in *BindTagsToUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 给指定标签批量关联用户
	BindUsersToTag(ctx context.Context, in *BindUsersToTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 从指定用户解除与多个标签的关联
	UnbindTagsFromUser(ctx context.Context, in *UnbindTagsFromUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 从指定标签解除与多个用户的关联
	UnbindUsersFromTag(ctx context.Context, in *UnbindUsersFromTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 创建标签
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagDetail, error)
	// 获取标签详情
	GetTagDetail(ctx context.Context, in *GetTagDetailRequest, opts ...grpc.CallOption) (*TagDetail, error)
	// 获取标签列表
	GetTagList(ctx context.Context, in *GetTagListRequest, opts ...grpc.CallOption) (*GetTagListResponse, error)
	// 更新标签
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除标签
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type metaEggLayoutClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaEggLayoutClient(cc grpc.ClientConnInterface) MetaEggLayoutClient {
	return &metaEggLayoutClient{cc}
}

func (c *metaEggLayoutClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDetail)
	err := c.cc.Invoke(ctx, MetaEggLayout_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*UserDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDetail)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetUserDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListResponse)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) AddUserPhone(ctx context.Context, in *AddUserPhoneRequest, opts ...grpc.CallOption) (*UserPhoneDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPhoneDetail)
	err := c.cc.Invoke(ctx, MetaEggLayout_AddUserPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) RemoveUserPhone(ctx context.Context, in *RemoveUserPhoneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_RemoveUserPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetAllUserPhone(ctx context.Context, in *GetAllUserPhoneRequest, opts ...grpc.CallOption) (*GetAllUserPhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUserPhoneResponse)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetAllUserPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetTagListByUserID(ctx context.Context, in *GetTagListByUserIDRequest, opts ...grpc.CallOption) (*GetTagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagListResponse)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetTagListByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetUserListByTagID(ctx context.Context, in *GetUserListByTagIDRequest, opts ...grpc.CallOption) (*GetUserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListResponse)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetUserListByTagID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) BindTagsToUser(ctx context.Context, in *BindTagsToUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_BindTagsToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) BindUsersToTag(ctx context.Context, in *BindUsersToTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_BindUsersToTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) UnbindTagsFromUser(ctx context.Context, in *UnbindTagsFromUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_UnbindTagsFromUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) UnbindUsersFromTag(ctx context.Context, in *UnbindUsersFromTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_UnbindUsersFromTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetail)
	err := c.cc.Invoke(ctx, MetaEggLayout_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetTagDetail(ctx context.Context, in *GetTagDetailRequest, opts ...grpc.CallOption) (*TagDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetail)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetTagDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) GetTagList(ctx context.Context, in *GetTagListRequest, opts ...grpc.CallOption) (*GetTagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagListResponse)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetTagList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEggLayoutClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaEggLayout_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaEggLayoutServer is the server API for MetaEggLayout service.
// All implementations must embed UnimplementedMetaEggLayoutServer
// for forward compatibility.
type MetaEggLayoutServer interface {
	// 创建用户
	CreateUser(context.Context, *CreateUserRequest) (*UserDetail, error)
	// 获取用户详情
	GetUserDetail(context.Context, *GetUserDetailRequest) (*UserDetail, error)
	// 获取用户列表
	GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error)
	// 更新用户
	UpdateUser(context.Context, *UpdateUserRequest) (*emptypb.Empty, error)
	// 删除用户
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	// 添加用户电话
	AddUserPhone(context.Context, *AddUserPhoneRequest) (*UserPhoneDetail, error)
	// 删除用户电话
	RemoveUserPhone(context.Context, *RemoveUserPhoneRequest) (*emptypb.Empty, error)
	// 获取所有用户电话
	GetAllUserPhone(context.Context, *GetAllUserPhoneRequest) (*GetAllUserPhoneResponse, error)
	// 获取与指定用户关联的标签列表
	GetTagListByUserID(context.Context, *GetTagListByUserIDRequest) (*GetTagListResponse, error)
	// 获取与指定标签关联的用户列表
	GetUserListByTagID(context.Context, *GetUserListByTagIDRequest) (*GetUserListResponse, error)
	// 给指定用户批量关联标签
	BindTagsToUser(context.Context, *BindTagsToUserRequest) (*emptypb.Empty, error)
	// 给指定标签批量关联用户
	BindUsersToTag(context.Context, *BindUsersToTagRequest) (*emptypb.Empty, error)
	// 从指定用户解除与多个标签的关联
	UnbindTagsFromUser(context.Context, *UnbindTagsFromUserRequest) (*emptypb.Empty, error)
	// 从指定标签解除与多个用户的关联
	UnbindUsersFromTag(context.Context, *UnbindUsersFromTagRequest) (*emptypb.Empty, error)
	// 创建标签
	CreateTag(context.Context, *CreateTagRequest) (*TagDetail, error)
	// 获取标签详情
	GetTagDetail(context.Context, *GetTagDetailRequest) (*TagDetail, error)
	// 获取标签列表
	GetTagList(context.Context, *GetTagListRequest) (*GetTagListResponse, error)
	// 更新标签
	UpdateTag(context.Context, *UpdateTagRequest) (*emptypb.Empty, error)
	// 删除标签
	DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMetaEggLayoutServer()
}

// UnimplementedMetaEggLayoutServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaEggLayoutServer struct{}

func (UnimplementedMetaEggLayoutServer) CreateUser(context.Context, *CreateUserRequest) (*UserDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetUserDetail(context.Context, *GetUserDetailRequest) (*UserDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedMetaEggLayoutServer) UpdateUser(context.Context, *UpdateUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedMetaEggLayoutServer) DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedMetaEggLayoutServer) AddUserPhone(context.Context, *AddUserPhoneRequest) (*UserPhoneDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserPhone not implemented")
}
func (UnimplementedMetaEggLayoutServer) RemoveUserPhone(context.Context, *RemoveUserPhoneRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserPhone not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetAllUserPhone(context.Context, *GetAllUserPhoneRequest) (*GetAllUserPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserPhone not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetTagListByUserID(context.Context, *GetTagListByUserIDRequest) (*GetTagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagListByUserID not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetUserListByTagID(context.Context, *GetUserListByTagIDRequest) (*GetUserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserListByTagID not implemented")
}
func (UnimplementedMetaEggLayoutServer) BindTagsToUser(context.Context, *BindTagsToUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindTagsToUser not implemented")
}
func (UnimplementedMetaEggLayoutServer) BindUsersToTag(context.Context, *BindUsersToTagRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindUsersToTag not implemented")
}
func (UnimplementedMetaEggLayoutServer) UnbindTagsFromUser(context.Context, *UnbindTagsFromUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindTagsFromUser not implemented")
}
func (UnimplementedMetaEggLayoutServer) UnbindUsersFromTag(context.Context, *UnbindUsersFromTagRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindUsersFromTag not implemented")
}
func (UnimplementedMetaEggLayoutServer) CreateTag(context.Context, *CreateTagRequest) (*TagDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetTagDetail(context.Context, *GetTagDetailRequest) (*TagDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagDetail not implemented")
}
func (UnimplementedMetaEggLayoutServer) GetTagList(context.Context, *GetTagListRequest) (*GetTagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagList not implemented")
}
func (UnimplementedMetaEggLayoutServer) UpdateTag(context.Context, *UpdateTagRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedMetaEggLayoutServer) DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedMetaEggLayoutServer) mustEmbedUnimplementedMetaEggLayoutServer() {}
func (UnimplementedMetaEggLayoutServer) testEmbeddedByValue()                       {}

// UnsafeMetaEggLayoutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaEggLayoutServer will
// result in compilation errors.
type UnsafeMetaEggLayoutServer interface {
	mustEmbedUnimplementedMetaEggLayoutServer()
}

func RegisterMetaEggLayoutServer(s grpc.ServiceRegistrar, srv MetaEggLayoutServer) {
	// If the following call pancis, it indicates UnimplementedMetaEggLayoutServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaEggLayout_ServiceDesc, srv)
}

func _MetaEggLayout_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetUserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetUserDetail(ctx, req.(*GetUserDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetUserList(ctx, req.(*GetUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_AddUserPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).AddUserPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_AddUserPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).AddUserPhone(ctx, req.(*AddUserPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_RemoveUserPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).RemoveUserPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_RemoveUserPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).RemoveUserPhone(ctx, req.(*RemoveUserPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetAllUserPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetAllUserPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetAllUserPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetAllUserPhone(ctx, req.(*GetAllUserPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetTagListByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagListByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetTagListByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetTagListByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetTagListByUserID(ctx, req.(*GetTagListByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetUserListByTagID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListByTagIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetUserListByTagID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetUserListByTagID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetUserListByTagID(ctx, req.(*GetUserListByTagIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_BindTagsToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindTagsToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).BindTagsToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_BindTagsToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).BindTagsToUser(ctx, req.(*BindTagsToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_BindUsersToTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUsersToTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).BindUsersToTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_BindUsersToTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).BindUsersToTag(ctx, req.(*BindUsersToTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_UnbindTagsFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindTagsFromUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).UnbindTagsFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_UnbindTagsFromUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).UnbindTagsFromUser(ctx, req.(*UnbindTagsFromUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_UnbindUsersFromTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindUsersFromTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).UnbindUsersFromTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_UnbindUsersFromTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).UnbindUsersFromTag(ctx, req.(*UnbindUsersFromTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetTagDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetTagDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetTagDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetTagDetail(ctx, req.(*GetTagDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_GetTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetTagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetTagList(ctx, req.(*GetTagListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEggLayout_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaEggLayout_ServiceDesc is the grpc.ServiceDesc for MetaEggLayout service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaEggLayout_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metaegglayout.MetaEggLayout",
	HandlerType: (*MetaEggLayoutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MetaEggLayout_CreateUser_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _MetaEggLayout_GetUserDetail_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _MetaEggLayout_GetUserList_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _MetaEggLayout_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _MetaEggLayout_DeleteUser_Handler,
		},
		{
			MethodName: "AddUserPhone",
			Handler:    _MetaEggLayout_AddUserPhone_Handler,
		},
		{
			MethodName: "RemoveUserPhone",
			Handler:    _MetaEggLayout_RemoveUserPhone_Handler,
		},
		{
			MethodName: "GetAllUserPhone",
			Handler:    _MetaEggLayout_GetAllUserPhone_Handler,
		},
		{
			MethodName: "GetTagListByUserID",
			Handler:    _MetaEggLayout_GetTagListByUserID_Handler,
		},
		{
			MethodName: "GetUserListByTagID",
			Handler:    _MetaEggLayout_GetUserListByTagID_Handler,
		},
		{
			MethodName: "BindTagsToUser",
			Handler:    _MetaEggLayout_BindTagsToUser_Handler,
		},
		{
			MethodName: "BindUsersToTag",
			Handler:    _MetaEggLayout_BindUsersToTag_Handler,
		},
		{
			MethodName: "UnbindTagsFromUser",
			Handler:    _MetaEggLayout_UnbindTagsFromUser_Handler,
		},
		{
			MethodName: "UnbindUsersFromTag",
			Handler:    _MetaEggLayout_UnbindUsersFromTag_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _MetaEggLayout_CreateTag_Handler,
		},
		{
			MethodName: "GetTagDetail",
			Handler:    _MetaEggLayout_GetTagDetail_Handler,
		},
		{
			MethodName: "GetTagList",
			Handler:    _MetaEggLayout_GetTagList_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _MetaEggLayout_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _MetaEggLayout_DeleteTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta_egg_layout.proto",
}
