// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.1
// source: meta_egg_layout.proto

package meta_egg_layout

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetaEggLayout_GetUserDetail_FullMethodName = "/metaegglayout.MetaEggLayout/GetUserDetail"
)

// MetaEggLayoutClient is the client API for MetaEggLayout service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaEggLayoutClient interface {
	// 获取用户详情
	GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*GetUserDetailResponse, error)
}

type metaEggLayoutClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaEggLayoutClient(cc grpc.ClientConnInterface) MetaEggLayoutClient {
	return &metaEggLayoutClient{cc}
}

func (c *metaEggLayoutClient) GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*GetUserDetailResponse, error) {
	out := new(GetUserDetailResponse)
	err := c.cc.Invoke(ctx, MetaEggLayout_GetUserDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaEggLayoutServer is the server API for MetaEggLayout service.
// All implementations must embed UnimplementedMetaEggLayoutServer
// for forward compatibility
type MetaEggLayoutServer interface {
	// 获取用户详情
	GetUserDetail(context.Context, *GetUserDetailRequest) (*GetUserDetailResponse, error)
	mustEmbedUnimplementedMetaEggLayoutServer()
}

// UnimplementedMetaEggLayoutServer must be embedded to have forward compatible implementations.
type UnimplementedMetaEggLayoutServer struct {
}

func (UnimplementedMetaEggLayoutServer) GetUserDetail(context.Context, *GetUserDetailRequest) (*GetUserDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (UnimplementedMetaEggLayoutServer) mustEmbedUnimplementedMetaEggLayoutServer() {}

// UnsafeMetaEggLayoutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaEggLayoutServer will
// result in compilation errors.
type UnsafeMetaEggLayoutServer interface {
	mustEmbedUnimplementedMetaEggLayoutServer()
}

func RegisterMetaEggLayoutServer(s grpc.ServiceRegistrar, srv MetaEggLayoutServer) {
	s.RegisterService(&MetaEggLayout_ServiceDesc, srv)
}

func _MetaEggLayout_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEggLayoutServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEggLayout_GetUserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEggLayoutServer).GetUserDetail(ctx, req.(*GetUserDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaEggLayout_ServiceDesc is the grpc.ServiceDesc for MetaEggLayout service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaEggLayout_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metaegglayout.MetaEggLayout",
	HandlerType: (*MetaEggLayoutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserDetail",
			Handler:    _MetaEggLayout_GetUserDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta_egg_layout.proto",
}
