// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.1
// source: meta_egg_layout.proto

package meta_egg_layout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_meta_egg_layout_proto protoreflect.FileDescriptor

const file_meta_egg_layout_proto_rawDesc = "" +
	"\n" +
	"\x15meta_egg_layout.proto\x12\rmetaegglayout\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"user.proto\x1a\x0euser_tag.proto\x1a\ttag.proto2\xcb\f\n" +
	"\rMetaEggLayout\x12K\n" +
	"\n" +
	"CreateUser\x12 .metaegglayout.CreateUserRequest\x1a\x19.metaegglayout.UserDetail\"\x00\x12Q\n" +
	"\rGetUserDetail\x12#.metaegglayout.GetUserDetailRequest\x1a\x19.metaegglayout.UserDetail\"\x00\x12V\n" +
	"\vGetUserList\x12!.metaegglayout.GetUserListRequest\x1a\".metaegglayout.GetUserListResponse\"\x00\x12H\n" +
	"\n" +
	"UpdateUser\x12 .metaegglayout.UpdateUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\n" +
	"DeleteUser\x12 .metaegglayout.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\fAddUserPhone\x12\".metaegglayout.AddUserPhoneRequest\x1a\x1e.metaegglayout.UserPhoneDetail\"\x00\x12R\n" +
	"\x0fRemoveUserPhone\x12%.metaegglayout.RemoveUserPhoneRequest\x1a\x16.google.protobuf.Empty\"\x00\x12b\n" +
	"\x0fGetAllUserPhone\x12%.metaegglayout.GetAllUserPhoneRequest\x1a&.metaegglayout.GetAllUserPhoneResponse\"\x00\x12c\n" +
	"\x12GetTagListByUserID\x12(.metaegglayout.GetTagListByUserIDRequest\x1a!.metaegglayout.GetTagListResponse\"\x00\x12d\n" +
	"\x12GetUserListByTagID\x12(.metaegglayout.GetUserListByTagIDRequest\x1a\".metaegglayout.GetUserListResponse\"\x00\x12P\n" +
	"\x0eBindTagsToUser\x12$.metaegglayout.BindTagsToUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12P\n" +
	"\x0eBindUsersToTag\x12$.metaegglayout.BindUsersToTagRequest\x1a\x16.google.protobuf.Empty\"\x00\x12X\n" +
	"\x12UnbindTagsFromUser\x12(.metaegglayout.UnbindTagsFromUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12X\n" +
	"\x12UnbindUsersFromTag\x12(.metaegglayout.UnbindUsersFromTagRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\tCreateTag\x12\x1f.metaegglayout.CreateTagRequest\x1a\x18.metaegglayout.TagDetail\"\x00\x12N\n" +
	"\fGetTagDetail\x12\".metaegglayout.GetTagDetailRequest\x1a\x18.metaegglayout.TagDetail\"\x00\x12S\n" +
	"\n" +
	"GetTagList\x12 .metaegglayout.GetTagListRequest\x1a!.metaegglayout.GetTagListResponse\"\x00\x12F\n" +
	"\tUpdateTag\x12\x1f.metaegglayout.UpdateTagRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\tDeleteTag\x12\x1f.metaegglayout.DeleteTagRequest\x1a\x16.google.protobuf.Empty\"\x00B\x13Z\x11./meta_egg_layoutb\x06proto3"

var file_meta_egg_layout_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: metaegglayout.CreateUserRequest
	(*GetUserDetailRequest)(nil),      // 1: metaegglayout.GetUserDetailRequest
	(*GetUserListRequest)(nil),        // 2: metaegglayout.GetUserListRequest
	(*UpdateUserRequest)(nil),         // 3: metaegglayout.UpdateUserRequest
	(*DeleteUserRequest)(nil),         // 4: metaegglayout.DeleteUserRequest
	(*AddUserPhoneRequest)(nil),       // 5: metaegglayout.AddUserPhoneRequest
	(*RemoveUserPhoneRequest)(nil),    // 6: metaegglayout.RemoveUserPhoneRequest
	(*GetAllUserPhoneRequest)(nil),    // 7: metaegglayout.GetAllUserPhoneRequest
	(*GetTagListByUserIDRequest)(nil), // 8: metaegglayout.GetTagListByUserIDRequest
	(*GetUserListByTagIDRequest)(nil), // 9: metaegglayout.GetUserListByTagIDRequest
	(*BindTagsToUserRequest)(nil),     // 10: metaegglayout.BindTagsToUserRequest
	(*BindUsersToTagRequest)(nil),     // 11: metaegglayout.BindUsersToTagRequest
	(*UnbindTagsFromUserRequest)(nil), // 12: metaegglayout.UnbindTagsFromUserRequest
	(*UnbindUsersFromTagRequest)(nil), // 13: metaegglayout.UnbindUsersFromTagRequest
	(*CreateTagRequest)(nil),          // 14: metaegglayout.CreateTagRequest
	(*GetTagDetailRequest)(nil),       // 15: metaegglayout.GetTagDetailRequest
	(*GetTagListRequest)(nil),         // 16: metaegglayout.GetTagListRequest
	(*UpdateTagRequest)(nil),          // 17: metaegglayout.UpdateTagRequest
	(*DeleteTagRequest)(nil),          // 18: metaegglayout.DeleteTagRequest
	(*UserDetail)(nil),                // 19: metaegglayout.UserDetail
	(*GetUserListResponse)(nil),       // 20: metaegglayout.GetUserListResponse
	(*emptypb.Empty)(nil),             // 21: google.protobuf.Empty
	(*UserPhoneDetail)(nil),           // 22: metaegglayout.UserPhoneDetail
	(*GetAllUserPhoneResponse)(nil),   // 23: metaegglayout.GetAllUserPhoneResponse
	(*GetTagListResponse)(nil),        // 24: metaegglayout.GetTagListResponse
	(*TagDetail)(nil),                 // 25: metaegglayout.TagDetail
}
var file_meta_egg_layout_proto_depIdxs = []int32{
	0,  // 0: metaegglayout.MetaEggLayout.CreateUser:input_type -> metaegglayout.CreateUserRequest
	1,  // 1: metaegglayout.MetaEggLayout.GetUserDetail:input_type -> metaegglayout.GetUserDetailRequest
	2,  // 2: metaegglayout.MetaEggLayout.GetUserList:input_type -> metaegglayout.GetUserListRequest
	3,  // 3: metaegglayout.MetaEggLayout.UpdateUser:input_type -> metaegglayout.UpdateUserRequest
	4,  // 4: metaegglayout.MetaEggLayout.DeleteUser:input_type -> metaegglayout.DeleteUserRequest
	5,  // 5: metaegglayout.MetaEggLayout.AddUserPhone:input_type -> metaegglayout.AddUserPhoneRequest
	6,  // 6: metaegglayout.MetaEggLayout.RemoveUserPhone:input_type -> metaegglayout.RemoveUserPhoneRequest
	7,  // 7: metaegglayout.MetaEggLayout.GetAllUserPhone:input_type -> metaegglayout.GetAllUserPhoneRequest
	8,  // 8: metaegglayout.MetaEggLayout.GetTagListByUserID:input_type -> metaegglayout.GetTagListByUserIDRequest
	9,  // 9: metaegglayout.MetaEggLayout.GetUserListByTagID:input_type -> metaegglayout.GetUserListByTagIDRequest
	10, // 10: metaegglayout.MetaEggLayout.BindTagsToUser:input_type -> metaegglayout.BindTagsToUserRequest
	11, // 11: metaegglayout.MetaEggLayout.BindUsersToTag:input_type -> metaegglayout.BindUsersToTagRequest
	12, // 12: metaegglayout.MetaEggLayout.UnbindTagsFromUser:input_type -> metaegglayout.UnbindTagsFromUserRequest
	13, // 13: metaegglayout.MetaEggLayout.UnbindUsersFromTag:input_type -> metaegglayout.UnbindUsersFromTagRequest
	14, // 14: metaegglayout.MetaEggLayout.CreateTag:input_type -> metaegglayout.CreateTagRequest
	15, // 15: metaegglayout.MetaEggLayout.GetTagDetail:input_type -> metaegglayout.GetTagDetailRequest
	16, // 16: metaegglayout.MetaEggLayout.GetTagList:input_type -> metaegglayout.GetTagListRequest
	17, // 17: metaegglayout.MetaEggLayout.UpdateTag:input_type -> metaegglayout.UpdateTagRequest
	18, // 18: metaegglayout.MetaEggLayout.DeleteTag:input_type -> metaegglayout.DeleteTagRequest
	19, // 19: metaegglayout.MetaEggLayout.CreateUser:output_type -> metaegglayout.UserDetail
	19, // 20: metaegglayout.MetaEggLayout.GetUserDetail:output_type -> metaegglayout.UserDetail
	20, // 21: metaegglayout.MetaEggLayout.GetUserList:output_type -> metaegglayout.GetUserListResponse
	21, // 22: metaegglayout.MetaEggLayout.UpdateUser:output_type -> google.protobuf.Empty
	21, // 23: metaegglayout.MetaEggLayout.DeleteUser:output_type -> google.protobuf.Empty
	22, // 24: metaegglayout.MetaEggLayout.AddUserPhone:output_type -> metaegglayout.UserPhoneDetail
	21, // 25: metaegglayout.MetaEggLayout.RemoveUserPhone:output_type -> google.protobuf.Empty
	23, // 26: metaegglayout.MetaEggLayout.GetAllUserPhone:output_type -> metaegglayout.GetAllUserPhoneResponse
	24, // 27: metaegglayout.MetaEggLayout.GetTagListByUserID:output_type -> metaegglayout.GetTagListResponse
	20, // 28: metaegglayout.MetaEggLayout.GetUserListByTagID:output_type -> metaegglayout.GetUserListResponse
	21, // 29: metaegglayout.MetaEggLayout.BindTagsToUser:output_type -> google.protobuf.Empty
	21, // 30: metaegglayout.MetaEggLayout.BindUsersToTag:output_type -> google.protobuf.Empty
	21, // 31: metaegglayout.MetaEggLayout.UnbindTagsFromUser:output_type -> google.protobuf.Empty
	21, // 32: metaegglayout.MetaEggLayout.UnbindUsersFromTag:output_type -> google.protobuf.Empty
	25, // 33: metaegglayout.MetaEggLayout.CreateTag:output_type -> metaegglayout.TagDetail
	25, // 34: metaegglayout.MetaEggLayout.GetTagDetail:output_type -> metaegglayout.TagDetail
	24, // 35: metaegglayout.MetaEggLayout.GetTagList:output_type -> metaegglayout.GetTagListResponse
	21, // 36: metaegglayout.MetaEggLayout.UpdateTag:output_type -> google.protobuf.Empty
	21, // 37: metaegglayout.MetaEggLayout.DeleteTag:output_type -> google.protobuf.Empty
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_meta_egg_layout_proto_init() }
func file_meta_egg_layout_proto_init() {
	if File_meta_egg_layout_proto != nil {
		return
	}
	file_user_proto_init()
	file_user_tag_proto_init()
	file_tag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_egg_layout_proto_rawDesc), len(file_meta_egg_layout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meta_egg_layout_proto_goTypes,
		DependencyIndexes: file_meta_egg_layout_proto_depIdxs,
	}.Build()
	File_meta_egg_layout_proto = out.File
	file_meta_egg_layout_proto_goTypes = nil
	file_meta_egg_layout_proto_depIdxs = nil
}
