// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.1
// source: tag.proto

package meta_egg_layout

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TagDetail 标签详情
type TagDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    //
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 标签名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDetail) Reset() {
	*x = TagDetail{}
	mi := &file_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDetail) ProtoMessage() {}

func (x *TagDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDetail.ProtoReflect.Descriptor instead.
func (*TagDetail) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateTagRequest 创建标签请求
type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

// GetTagDetailRequest 获取标签详情请求
type GetTagDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标签ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagDetailRequest) Reset() {
	*x = GetTagDetailRequest{}
	mi := &file_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagDetailRequest) ProtoMessage() {}

func (x *GetTagDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagDetailRequest.ProtoReflect.Descriptor instead.
func (*GetTagDetailRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *GetTagDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TagListInfo 标签列表信息
type TagListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    //
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 标签名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListInfo) Reset() {
	*x = TagListInfo{}
	mi := &file_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListInfo) ProtoMessage() {}

func (x *TagListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListInfo.ProtoReflect.Descriptor instead.
func (*TagListInfo) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{3}
}

func (x *TagListInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagListInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetTagListRequest 获取标签列表请求
type GetTagListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页请求（可选, 不传则不分页）
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	// 排序字段, 可选: id
	OrderBy *string `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	// 排序方式, 默认 desc, 可选: asc, desc
	OrderType     *string `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3,oneof" json:"order_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagListRequest) Reset() {
	*x = GetTagListRequest{}
	mi := &file_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListRequest) ProtoMessage() {}

func (x *GetTagListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListRequest.ProtoReflect.Descriptor instead.
func (*GetTagListRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{4}
}

func (x *GetTagListRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTagListRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetTagListRequest) GetOrderType() string {
	if x != nil && x.OrderType != nil {
		return *x.OrderType
	}
	return ""
}

// GetTagListResponse 获取标签列表响应
type GetTagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TagListInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 列表数据
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 结果集总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagListResponse) Reset() {
	*x = GetTagListResponse{}
	mi := &file_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListResponse) ProtoMessage() {}

func (x *GetTagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListResponse.ProtoReflect.Descriptor instead.
func (*GetTagListResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{5}
}

func (x *GetTagListResponse) GetList() []*TagListInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetTagListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateTagRequest 更新标签请求
type UpdateTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标签ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTagRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTagRequest 删除标签请求
type DeleteTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标签ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTagRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_tag_proto protoreflect.FileDescriptor

const file_tag_proto_rawDesc = "" +
	"\n" +
	"\ttag.proto\x12\rmetaegglayout\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\x1a\x1cmeta_egg_layout_common.proto\"/\n" +
	"\tTagDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x12\n" +
	"\x10CreateTagRequest\".\n" +
	"\x13GetTagDetailRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x02id\"1\n" +
	"\vTagListInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xdf\x01\n" +
	"\x11GetTagListRequest\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.metaegglayout.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x12)\n" +
	"\border_by\x18\x02 \x01(\tB\t\xfaB\x06r\x04R\x02idH\x01R\aorderBy\x88\x01\x01\x124\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tB\x10\xfaB\rr\vR\x03ascR\x04descH\x02R\torderType\x88\x01\x01B\r\n" +
	"\v_paginationB\v\n" +
	"\t_order_byB\r\n" +
	"\v_order_type\"Z\n" +
	"\x12GetTagListResponse\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.metaegglayout.TagListInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"+\n" +
	"\x10UpdateTagRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x02id\"+\n" +
	"\x10DeleteTagRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x02idB\x13Z\x11./meta_egg_layoutb\x06proto3"

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData []byte
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)))
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tag_proto_goTypes = []any{
	(*TagDetail)(nil),           // 0: metaegglayout.TagDetail
	(*CreateTagRequest)(nil),    // 1: metaegglayout.CreateTagRequest
	(*GetTagDetailRequest)(nil), // 2: metaegglayout.GetTagDetailRequest
	(*TagListInfo)(nil),         // 3: metaegglayout.TagListInfo
	(*GetTagListRequest)(nil),   // 4: metaegglayout.GetTagListRequest
	(*GetTagListResponse)(nil),  // 5: metaegglayout.GetTagListResponse
	(*UpdateTagRequest)(nil),    // 6: metaegglayout.UpdateTagRequest
	(*DeleteTagRequest)(nil),    // 7: metaegglayout.DeleteTagRequest
	(*Pagination)(nil),          // 8: metaegglayout.Pagination
}
var file_tag_proto_depIdxs = []int32{
	8, // 0: metaegglayout.GetTagListRequest.pagination:type_name -> metaegglayout.Pagination
	3, // 1: metaegglayout.GetTagListResponse.list:type_name -> metaegglayout.TagListInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	file_meta_egg_layout_common_proto_init()
	file_tag_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
