// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.1
// source: user.proto

package meta_egg_layout

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserDetail 用户详情
type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      //
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`                             // 用户名
	Gender        uint64                 `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`                              // 性别
	Age           uint32                 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`                                    // 年龄
	IsOnJob       bool                   `protobuf:"varint,5,opt,name=is_on_job,json=isOnJob,proto3" json:"is_on_job,omitempty"`           // 是否在职
	Birthday      *string                `protobuf:"bytes,6,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`                     // 生日
	CreatedBy     *uint64                `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"` // 创建者
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间
	UpdatedBy     *uint64                `protobuf:"varint,9,opt,name=updated_by,json=updatedBy,proto3,oneof" json:"updated_by,omitempty"` // 更新者
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // 更新时间
	UserPhones    []*UserPhoneDetail     `protobuf:"bytes,11,rep,name=user_phones,json=userPhones,proto3" json:"user_phones,omitempty"`    // 用户电话列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetail) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserDetail) GetGender() uint64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserDetail) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserDetail) GetIsOnJob() bool {
	if x != nil {
		return x.IsOnJob
	}
	return false
}

func (x *UserDetail) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *UserDetail) GetCreatedBy() uint64 {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return 0
}

func (x *UserDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserDetail) GetUpdatedBy() uint64 {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return 0
}

func (x *UserDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserDetail) GetUserPhones() []*UserPhoneDetail {
	if x != nil {
		return x.UserPhones
	}
	return nil
}

// CreateUserRequest 创建用户请求
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 性别
	Gender uint64 `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	// 年龄
	Age uint32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// 是否在职
	IsOnJob bool `protobuf:"varint,4,opt,name=is_on_job,json=isOnJob,proto3" json:"is_on_job,omitempty"`
	// 生日 格式: 2006-01-02
	Birthday *string `protobuf:"bytes,5,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	// 用户电话数据列表（可选）
	UserPhones    []*UserPhoneCreateData `protobuf:"bytes,12,rep,name=user_phones,json=userPhones,proto3" json:"user_phones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetGender() uint64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateUserRequest) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetIsOnJob() bool {
	if x != nil {
		return x.IsOnJob
	}
	return false
}

func (x *CreateUserRequest) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *CreateUserRequest) GetUserPhones() []*UserPhoneCreateData {
	if x != nil {
		return x.UserPhones
	}
	return nil
}

// GetUserDetailRequest 获取用户详情请求
type GetUserDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailRequest) Reset() {
	*x = GetUserDetailRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailRequest) ProtoMessage() {}

func (x *GetUserDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailRequest.ProtoReflect.Descriptor instead.
func (*GetUserDetailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UserListInfo 用户列表信息
type UserListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   //
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`                          // 用户名
	Gender        uint64                 `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`                           // 性别
	UserPhones    []*UserPhoneListInfo   `protobuf:"bytes,11,rep,name=user_phones,json=userPhones,proto3" json:"user_phones,omitempty"` // 用户电话列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListInfo) Reset() {
	*x = UserListInfo{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInfo) ProtoMessage() {}

func (x *UserListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInfo.ProtoReflect.Descriptor instead.
func (*UserListInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserListInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserListInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserListInfo) GetGender() uint64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserListInfo) GetUserPhones() []*UserPhoneListInfo {
	if x != nil {
		return x.UserPhones
	}
	return nil
}

// GetUserListRequest 获取用户列表请求
type GetUserListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页请求（可选, 不传则不分页）
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	// 筛选项: 性别 (可选)
	Gender *uint64 `protobuf:"varint,2,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	// 筛选项: 是否在职 (可选)
	IsOnJob *bool `protobuf:"varint,3,opt,name=is_on_job,json=isOnJob,proto3,oneof" json:"is_on_job,omitempty"`
	// 排序字段, 可选: id
	OrderBy *string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	// 排序方式, 默认 desc, 可选: asc, desc
	OrderType     *string `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3,oneof" json:"order_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListRequest) Reset() {
	*x = GetUserListRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRequest) ProtoMessage() {}

func (x *GetUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRequest.ProtoReflect.Descriptor instead.
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserListRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserListRequest) GetGender() uint64 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *GetUserListRequest) GetIsOnJob() bool {
	if x != nil && x.IsOnJob != nil {
		return *x.IsOnJob
	}
	return false
}

func (x *GetUserListRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetUserListRequest) GetOrderType() string {
	if x != nil && x.OrderType != nil {
		return *x.OrderType
	}
	return ""
}

// GetUserListResponse 获取用户列表响应
type GetUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserListInfo        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 列表数据
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 结果集总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListResponse) Reset() {
	*x = GetUserListResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListResponse) ProtoMessage() {}

func (x *GetUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListResponse.ProtoReflect.Descriptor instead.
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserListResponse) GetList() []*UserListInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateUserRequest 更新用户请求
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 更新项: 用户名 (可选)
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 更新项: 性别 (可选)
	Gender *uint64 `protobuf:"varint,3,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	// 更新项: 年龄 (可选)
	Age *uint32 `protobuf:"varint,4,opt,name=age,proto3,oneof" json:"age,omitempty"`
	// 更新项: 是否在职 (可选)
	IsOnJob *bool `protobuf:"varint,5,opt,name=is_on_job,json=isOnJob,proto3,oneof" json:"is_on_job,omitempty"`
	// 更新项: 生日 格式: 2006-01-02 (可选)
	Birthday      *string `protobuf:"bytes,6,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetGender() uint64 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UpdateUserRequest) GetAge() uint32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdateUserRequest) GetIsOnJob() bool {
	if x != nil && x.IsOnJob != nil {
		return *x.IsOnJob
	}
	return false
}

func (x *UpdateUserRequest) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

// DeleteUserRequest 删除用户请求
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UserPhoneDetail 用户电话详情
type UserPhoneDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      //
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`  // 电话号码
	CreatedBy     *uint64                `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"` // 创建者
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPhoneDetail) Reset() {
	*x = UserPhoneDetail{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPhoneDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPhoneDetail) ProtoMessage() {}

func (x *UserPhoneDetail) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPhoneDetail.ProtoReflect.Descriptor instead.
func (*UserPhoneDetail) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserPhoneDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPhoneDetail) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPhoneDetail) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserPhoneDetail) GetCreatedBy() uint64 {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return 0
}

func (x *UserPhoneDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// UserPhoneListInfo 用户电话列表信息
type UserPhoneListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     //
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // 电话号码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPhoneListInfo) Reset() {
	*x = UserPhoneListInfo{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPhoneListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPhoneListInfo) ProtoMessage() {}

func (x *UserPhoneListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPhoneListInfo.ProtoReflect.Descriptor instead.
func (*UserPhoneListInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserPhoneListInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPhoneListInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPhoneListInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// UserPhoneCreateData 用户电话创建数据
type UserPhoneCreateData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 电话号码
	PhoneNumber   string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPhoneCreateData) Reset() {
	*x = UserPhoneCreateData{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPhoneCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPhoneCreateData) ProtoMessage() {}

func (x *UserPhoneCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPhoneCreateData.ProtoReflect.Descriptor instead.
func (*UserPhoneCreateData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserPhoneCreateData) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// AddUserPhoneRequest 添加用户电话请求
type AddUserPhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 电话号码
	PhoneNumber   string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserPhoneRequest) Reset() {
	*x = AddUserPhoneRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserPhoneRequest) ProtoMessage() {}

func (x *AddUserPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserPhoneRequest.ProtoReflect.Descriptor instead.
func (*AddUserPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddUserPhoneRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddUserPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// RemoveUserPhoneRequest 删除用户电话请求
type RemoveUserPhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 用户电话ID
	UserPhoneId   uint64 `protobuf:"varint,2,opt,name=user_phone_id,json=userPhoneId,proto3" json:"user_phone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserPhoneRequest) Reset() {
	*x = RemoveUserPhoneRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserPhoneRequest) ProtoMessage() {}

func (x *RemoveUserPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserPhoneRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveUserPhoneRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveUserPhoneRequest) GetUserPhoneId() uint64 {
	if x != nil {
		return x.UserPhoneId
	}
	return 0
}

// GetAllUserPhoneRequest 获取所有用户电话请求
type GetAllUserPhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId        uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserPhoneRequest) Reset() {
	*x = GetAllUserPhoneRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserPhoneRequest) ProtoMessage() {}

func (x *GetAllUserPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllUserPhoneRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetAllUserPhoneResponse 获取所有用户电话响应
type GetAllUserPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserPhoneDetail     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 用户电话列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserPhoneResponse) Reset() {
	*x = GetAllUserPhoneResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserPhoneResponse) ProtoMessage() {}

func (x *GetAllUserPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserPhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllUserPhoneResponse) GetList() []*UserPhoneDetail {
	if x != nil {
		return x.List
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\rmetaegglayout\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\x1a\x1cmeta_egg_layout_common.proto\"\x97\x03\n" +
	"\n" +
	"UserDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x04R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\rR\x03age\x12\x1a\n" +
	"\tis_on_job\x18\x05 \x01(\bR\aisOnJob\x12\x1f\n" +
	"\bbirthday\x18\x06 \x01(\tH\x01R\bbirthday\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\a \x01(\x04H\x02R\tcreatedBy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"updated_by\x18\t \x01(\x04H\x03R\tupdatedBy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12?\n" +
	"\vuser_phones\x18\v \x03(\v2\x1e.metaegglayout.UserPhoneDetailR\n" +
	"userPhonesB\a\n" +
	"\x05_nameB\v\n" +
	"\t_birthdayB\r\n" +
	"\v_created_byB\r\n" +
	"\v_updated_by\"\x9c\x02\n" +
	"\x11CreateUserRequest\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x18@H\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\x06gender\x18\x02 \x01(\x04B\a\xfaB\x042\x02(\x01R\x06gender\x12\x10\n" +
	"\x03age\x18\x03 \x01(\rR\x03age\x12\x1a\n" +
	"\tis_on_job\x18\x04 \x01(\bR\aisOnJob\x12;\n" +
	"\bbirthday\x18\x05 \x01(\tB\x1a\xfaB\x17r\x152\x13^\\d{4}-\\d{2}-\\d{2}$H\x01R\bbirthday\x88\x01\x01\x12C\n" +
	"\vuser_phones\x18\f \x03(\v2\".metaegglayout.UserPhoneCreateDataR\n" +
	"userPhonesB\a\n" +
	"\x05_nameB\v\n" +
	"\t_birthday\"/\n" +
	"\x14GetUserDetailRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x02id\"\x9b\x01\n" +
	"\fUserListInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x04R\x06gender\x12A\n" +
	"\vuser_phones\x18\v \x03(\v2 .metaegglayout.UserPhoneListInfoR\n" +
	"userPhonesB\a\n" +
	"\x05_name\"\xc0\x02\n" +
	"\x12GetUserListRequest\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.metaegglayout.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x12$\n" +
	"\x06gender\x18\x02 \x01(\x04B\a\xfaB\x042\x02(\x01H\x01R\x06gender\x88\x01\x01\x12\x1f\n" +
	"\tis_on_job\x18\x03 \x01(\bH\x02R\aisOnJob\x88\x01\x01\x12)\n" +
	"\border_by\x18\x04 \x01(\tB\t\xfaB\x06r\x04R\x02idH\x03R\aorderBy\x88\x01\x01\x124\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tB\x10\xfaB\rr\vR\x03ascR\x04descH\x04R\torderType\x88\x01\x01B\r\n" +
	"\v_paginationB\t\n" +
	"\a_genderB\f\n" +
	"\n" +
	"_is_on_jobB\v\n" +
	"\t_order_byB\r\n" +
	"\v_order_type\"\\\n" +
	"\x13GetUserListResponse\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.metaegglayout.UserListInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa0\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x02id\x12 \n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18@H\x00R\x04name\x88\x01\x01\x12$\n" +
	"\x06gender\x18\x03 \x01(\x04B\a\xfaB\x042\x02(\x01H\x01R\x06gender\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x04 \x01(\rH\x02R\x03age\x88\x01\x01\x12\x1f\n" +
	"\tis_on_job\x18\x05 \x01(\bH\x03R\aisOnJob\x88\x01\x01\x12;\n" +
	"\bbirthday\x18\x06 \x01(\tB\x1a\xfaB\x17r\x152\x13^\\d{4}-\\d{2}-\\d{2}$H\x04R\bbirthday\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_genderB\x06\n" +
	"\x04_ageB\f\n" +
	"\n" +
	"_is_on_jobB\v\n" +
	"\t_birthday\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x02id\"\xaf\x01\n" +
	"\x0fUserPhoneDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\"\n" +
	"\n" +
	"created_by\x18\x04 \x01(\x04H\x00R\tcreatedBy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAtB\r\n" +
	"\v_created_by\"_\n" +
	"\x11UserPhoneListInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\"A\n" +
	"\x13UserPhoneCreateData\x12*\n" +
	"\fphone_number\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x18\x14R\vphoneNumber\"c\n" +
	"\x13AddUserPhoneRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x06userId\x12*\n" +
	"\fphone_number\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18\x14R\vphoneNumber\"g\n" +
	"\x16RemoveUserPhoneRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x06userId\x12+\n" +
	"\ruser_phone_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02(\x01R\vuserPhoneId\":\n" +
	"\x16GetAllUserPhoneRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x06userId\"M\n" +
	"\x17GetAllUserPhoneResponse\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.metaegglayout.UserPhoneDetailR\x04listB\x13Z\x11./meta_egg_layoutb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_proto_goTypes = []any{
	(*UserDetail)(nil),              // 0: metaegglayout.UserDetail
	(*CreateUserRequest)(nil),       // 1: metaegglayout.CreateUserRequest
	(*GetUserDetailRequest)(nil),    // 2: metaegglayout.GetUserDetailRequest
	(*UserListInfo)(nil),            // 3: metaegglayout.UserListInfo
	(*GetUserListRequest)(nil),      // 4: metaegglayout.GetUserListRequest
	(*GetUserListResponse)(nil),     // 5: metaegglayout.GetUserListResponse
	(*UpdateUserRequest)(nil),       // 6: metaegglayout.UpdateUserRequest
	(*DeleteUserRequest)(nil),       // 7: metaegglayout.DeleteUserRequest
	(*UserPhoneDetail)(nil),         // 8: metaegglayout.UserPhoneDetail
	(*UserPhoneListInfo)(nil),       // 9: metaegglayout.UserPhoneListInfo
	(*UserPhoneCreateData)(nil),     // 10: metaegglayout.UserPhoneCreateData
	(*AddUserPhoneRequest)(nil),     // 11: metaegglayout.AddUserPhoneRequest
	(*RemoveUserPhoneRequest)(nil),  // 12: metaegglayout.RemoveUserPhoneRequest
	(*GetAllUserPhoneRequest)(nil),  // 13: metaegglayout.GetAllUserPhoneRequest
	(*GetAllUserPhoneResponse)(nil), // 14: metaegglayout.GetAllUserPhoneResponse
	(*Pagination)(nil),              // 15: metaegglayout.Pagination
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: metaegglayout.UserDetail.user_phones:type_name -> metaegglayout.UserPhoneDetail
	10, // 1: metaegglayout.CreateUserRequest.user_phones:type_name -> metaegglayout.UserPhoneCreateData
	9,  // 2: metaegglayout.UserListInfo.user_phones:type_name -> metaegglayout.UserPhoneListInfo
	15, // 3: metaegglayout.GetUserListRequest.pagination:type_name -> metaegglayout.Pagination
	3,  // 4: metaegglayout.GetUserListResponse.list:type_name -> metaegglayout.UserListInfo
	8,  // 5: metaegglayout.GetAllUserPhoneResponse.list:type_name -> metaegglayout.UserPhoneDetail
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_meta_egg_layout_common_proto_init()
	file_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_user_proto_msgTypes[4].OneofWrappers = []any{}
	file_user_proto_msgTypes[6].OneofWrappers = []any{}
	file_user_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
