// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.1
// source: user_tag.proto

package meta_egg_layout

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagListByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`                // 分页请求（可选, 不传则不分页）
	OrderBy       *string                `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`       // 排序字段
	OrderType     *string                `protobuf:"bytes,4,opt,name=order_type,json=orderType,proto3,oneof" json:"order_type,omitempty"` // 排序类型: asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagListByUserIDRequest) Reset() {
	*x = GetTagListByUserIDRequest{}
	mi := &file_user_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagListByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListByUserIDRequest) ProtoMessage() {}

func (x *GetTagListByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetTagListByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_tag_proto_rawDescGZIP(), []int{0}
}

func (x *GetTagListByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTagListByUserIDRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTagListByUserIDRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetTagListByUserIDRequest) GetOrderType() string {
	if x != nil && x.OrderType != nil {
		return *x.OrderType
	}
	return ""
}

type GetUserListByTagIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint64                 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`                  // 标签ID
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`                // 分页请求（可选, 不传则不分页）
	Gender        *uint64                `protobuf:"varint,3,opt,name=gender,proto3,oneof" json:"gender,omitempty"`                       // 性别
	IsOnJob       *bool                  `protobuf:"varint,4,opt,name=isOnJob,proto3,oneof" json:"isOnJob,omitempty"`                     // 是否在职
	OrderBy       *string                `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`       // 排序字段
	OrderType     *string                `protobuf:"bytes,6,opt,name=order_type,json=orderType,proto3,oneof" json:"order_type,omitempty"` // 排序类型: asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListByTagIDRequest) Reset() {
	*x = GetUserListByTagIDRequest{}
	mi := &file_user_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListByTagIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListByTagIDRequest) ProtoMessage() {}

func (x *GetUserListByTagIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListByTagIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserListByTagIDRequest) Descriptor() ([]byte, []int) {
	return file_user_tag_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserListByTagIDRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *GetUserListByTagIDRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserListByTagIDRequest) GetGender() uint64 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *GetUserListByTagIDRequest) GetIsOnJob() bool {
	if x != nil && x.IsOnJob != nil {
		return *x.IsOnJob
	}
	return false
}

func (x *GetUserListByTagIDRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetUserListByTagIDRequest) GetOrderType() string {
	if x != nil && x.OrderType != nil {
		return *x.OrderType
	}
	return ""
}

type BindTagsToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`        // 用户ID
	TagIds        []uint64               `protobuf:"varint,2,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"` // 标签ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindTagsToUserRequest) Reset() {
	*x = BindTagsToUserRequest{}
	mi := &file_user_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindTagsToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTagsToUserRequest) ProtoMessage() {}

func (x *BindTagsToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTagsToUserRequest.ProtoReflect.Descriptor instead.
func (*BindTagsToUserRequest) Descriptor() ([]byte, []int) {
	return file_user_tag_proto_rawDescGZIP(), []int{2}
}

func (x *BindTagsToUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindTagsToUserRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type BindUsersToTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint64                 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`              // 标签ID
	UserIds       []uint64               `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindUsersToTagRequest) Reset() {
	*x = BindUsersToTagRequest{}
	mi := &file_user_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindUsersToTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindUsersToTagRequest) ProtoMessage() {}

func (x *BindUsersToTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindUsersToTagRequest.ProtoReflect.Descriptor instead.
func (*BindUsersToTagRequest) Descriptor() ([]byte, []int) {
	return file_user_tag_proto_rawDescGZIP(), []int{3}
}

func (x *BindUsersToTagRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *BindUsersToTagRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UnbindTagsFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`        // 用户ID
	TagIds        []uint64               `protobuf:"varint,2,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"` // 标签ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindTagsFromUserRequest) Reset() {
	*x = UnbindTagsFromUserRequest{}
	mi := &file_user_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindTagsFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindTagsFromUserRequest) ProtoMessage() {}

func (x *UnbindTagsFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindTagsFromUserRequest.ProtoReflect.Descriptor instead.
func (*UnbindTagsFromUserRequest) Descriptor() ([]byte, []int) {
	return file_user_tag_proto_rawDescGZIP(), []int{4}
}

func (x *UnbindTagsFromUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnbindTagsFromUserRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type UnbindUsersFromTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint64                 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`              // 标签ID
	UserIds       []uint64               `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindUsersFromTagRequest) Reset() {
	*x = UnbindUsersFromTagRequest{}
	mi := &file_user_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindUsersFromTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindUsersFromTagRequest) ProtoMessage() {}

func (x *UnbindUsersFromTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindUsersFromTagRequest.ProtoReflect.Descriptor instead.
func (*UnbindUsersFromTagRequest) Descriptor() ([]byte, []int) {
	return file_user_tag_proto_rawDescGZIP(), []int{5}
}

func (x *UnbindUsersFromTagRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *UnbindUsersFromTagRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_user_tag_proto protoreflect.FileDescriptor

const file_user_tag_proto_rawDesc = "" +
	"\n" +
	"\x0euser_tag.proto\x12\rmetaegglayout\x1a\x1bgoogle/protobuf/empty.proto\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\x1a\x1cmeta_egg_layout_common.proto\"\xe3\x01\n" +
	"\x19GetTagListByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.metaegglayout.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x03 \x01(\tH\x01R\aorderBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"order_type\x18\x04 \x01(\tH\x02R\torderType\x88\x01\x01B\r\n" +
	"\v_paginationB\v\n" +
	"\t_order_byB\r\n" +
	"\v_order_type\"\xb4\x02\n" +
	"\x19GetUserListByTagIDRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x04R\x05tagId\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.metaegglayout.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x03 \x01(\x04H\x01R\x06gender\x88\x01\x01\x12\x1d\n" +
	"\aisOnJob\x18\x04 \x01(\bH\x02R\aisOnJob\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tH\x03R\aorderBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"order_type\x18\x06 \x01(\tH\x04R\torderType\x88\x01\x01B\r\n" +
	"\v_paginationB\t\n" +
	"\a_genderB\n" +
	"\n" +
	"\b_isOnJobB\v\n" +
	"\t_order_byB\r\n" +
	"\v_order_type\"I\n" +
	"\x15BindTagsToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\atag_ids\x18\x02 \x03(\x04R\x06tagIds\"I\n" +
	"\x15BindUsersToTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x04R\x05tagId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x04R\auserIds\"M\n" +
	"\x19UnbindTagsFromUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\atag_ids\x18\x02 \x03(\x04R\x06tagIds\"M\n" +
	"\x19UnbindUsersFromTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x04R\x05tagId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x04R\auserIdsB\x13Z\x11./meta_egg_layoutb\x06proto3"

var (
	file_user_tag_proto_rawDescOnce sync.Once
	file_user_tag_proto_rawDescData []byte
)

func file_user_tag_proto_rawDescGZIP() []byte {
	file_user_tag_proto_rawDescOnce.Do(func() {
		file_user_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_tag_proto_rawDesc), len(file_user_tag_proto_rawDesc)))
	})
	return file_user_tag_proto_rawDescData
}

var file_user_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_tag_proto_goTypes = []any{
	(*GetTagListByUserIDRequest)(nil), // 0: metaegglayout.GetTagListByUserIDRequest
	(*GetUserListByTagIDRequest)(nil), // 1: metaegglayout.GetUserListByTagIDRequest
	(*BindTagsToUserRequest)(nil),     // 2: metaegglayout.BindTagsToUserRequest
	(*BindUsersToTagRequest)(nil),     // 3: metaegglayout.BindUsersToTagRequest
	(*UnbindTagsFromUserRequest)(nil), // 4: metaegglayout.UnbindTagsFromUserRequest
	(*UnbindUsersFromTagRequest)(nil), // 5: metaegglayout.UnbindUsersFromTagRequest
	(*Pagination)(nil),                // 6: metaegglayout.Pagination
}
var file_user_tag_proto_depIdxs = []int32{
	6, // 0: metaegglayout.GetTagListByUserIDRequest.pagination:type_name -> metaegglayout.Pagination
	6, // 1: metaegglayout.GetUserListByTagIDRequest.pagination:type_name -> metaegglayout.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_tag_proto_init() }
func file_user_tag_proto_init() {
	if File_user_tag_proto != nil {
		return
	}
	file_meta_egg_layout_common_proto_init()
	file_user_tag_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_tag_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_tag_proto_rawDesc), len(file_user_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_tag_proto_goTypes,
		DependencyIndexes: file_user_tag_proto_depIdxs,
		MessageInfos:      file_user_tag_proto_msgTypes,
	}.Build()
	File_user_tag_proto = out.File
	file_user_tag_proto_goTypes = nil
	file_user_tag_proto_depIdxs = nil
}
