definitions:
  internal_handler_http.ReqCreateUser:
    properties:
      age:
        description: 年龄
        type: integer
      birthday:
        description: '生日 格式: 2006-01-02'
        type: string
      gender:
        description: 性别
        minimum: 1
        type: integer
      is_on_job:
        description: 是否在职
        type: boolean
      name:
        description: 用户名
        maxLength: 64
        type: string
    required:
    - age
    - gender
    type: object
  internal_handler_http.ReqUpdateUser:
    properties:
      age:
        description: 年龄
        type: integer
      birthday:
        description: '生日 格式: 2006-01-02'
        type: string
      gender:
        description: 性别
        minimum: 1
        type: integer
      is_on_job:
        description: 是否在职
        type: boolean
      name:
        description: 用户名
        maxLength: 64
        type: string
    type: object
  internal_handler_http.RspBase:
    properties:
      code:
        $ref: '#/definitions/meta-egg-layout_api_meta_egg_layout.ErrCode'
      message:
        type: string
    type: object
  internal_handler_http.RspData:
    properties:
      code:
        $ref: '#/definitions/meta-egg-layout_api_meta_egg_layout.ErrCode'
      data: {}
      message:
        type: string
    type: object
  internal_handler_http.UserDetail:
    properties:
      age:
        description: 年龄
        type: integer
      birthday:
        description: 生日 (nullable)
        type: string
      created_at:
        description: 创建时间
        type: string
      created_by:
        description: 创建者 (nullable)
        type: integer
      gender:
        description: 性别
        type: integer
      id:
        type: integer
      is_on_job:
        description: 是否在职
        type: boolean
      name:
        description: 用户名 (nullable)
        type: string
      updated_at:
        description: 更新时间
        type: string
      updated_by:
        description: 更新者 (nullable)
        type: integer
    type: object
  internal_handler_http.UserList:
    properties:
      list:
        description: 用户列表
        items:
          $ref: '#/definitions/internal_handler_http.UserListInfo'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  internal_handler_http.UserListInfo:
    properties:
      gender:
        description: 性别
        type: integer
      id:
        type: integer
      name:
        description: 用户名 (nullable)
        type: string
    type: object
  meta-egg-layout_api_meta_egg_layout.ErrCode:
    enum:
    - 0
    - 2
    - 3
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 13
    - 14
    - 15
    - 16
    - 1000
    type: integer
    x-enum-comments:
      ErrCode_Aborted: 操作被中止
      ErrCode_AlreadyExists: 创建实体时冲突
      ErrCode_DataLoss: 数据丢失或损坏
      ErrCode_FailedPrecondition: 前置条件失败
      ErrCode_Internal: 内部错误
      ErrCode_InvalidArgument: 参数错
      ErrCode_MaxReservedErrCode: 预留错误码最大值
      ErrCode_NotFound: 实体不存在
      ErrCode_Ok: 成功
      ErrCode_OutOfRange: 超出范围
      ErrCode_PermissionDenied: 权限不足
      ErrCode_ResourceExhausted: 资源不足
      ErrCode_Unauthenticated: 未认证，客户端未提供凭据或提供的凭据无效
      ErrCode_Unavailable: 服务不可用，请重试
      ErrCode_Unknown: 未知错误
    x-enum-varnames:
    - ErrCode_Ok
    - ErrCode_Unknown
    - ErrCode_InvalidArgument
    - ErrCode_NotFound
    - ErrCode_AlreadyExists
    - ErrCode_PermissionDenied
    - ErrCode_ResourceExhausted
    - ErrCode_FailedPrecondition
    - ErrCode_Aborted
    - ErrCode_OutOfRange
    - ErrCode_Internal
    - ErrCode_Unavailable
    - ErrCode_DataLoss
    - ErrCode_Unauthenticated
    - ErrCode_MaxReservedErrCode
info:
  contact: {}
  title: meta-egg-layout
  version: xxx
paths:
  /api/v1/users:
    get:
      consumes:
      - application/json
      operationId: GetUserList
      parameters:
      - description: Bearer <jwt-token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: 页码, 从1开始
        in: query
        name: page
        required: true
        type: integer
      - description: 每页数量, 要求大于0
        in: query
        name: page_size
        required: true
        type: integer
      - description: 性别
        in: query
        name: gender
        type: integer
      - description: 是否在职
        in: query
        name: is_on_job
        type: boolean
      - description: '排序字段, 可选: id'
        in: query
        name: order_by
        type: string
      - description: 排序类型,默认desc
        in: query
        name: order_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal_handler_http.RspData'
            - properties:
                data:
                  $ref: '#/definitions/internal_handler_http.UserList'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
      summary: 获取用户列表
      tags:
      - 用户
    post:
      consumes:
      - application/json
      operationId: CreateUser
      parameters:
      - description: Bearer <jwt-token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_handler_http.ReqCreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal_handler_http.RspData'
            - properties:
                data:
                  $ref: '#/definitions/internal_handler_http.UserDetail'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
      summary: 创建用户
      tags:
      - 用户
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      operationId: DeleteUser
      parameters:
      - description: Bearer <jwt-token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
      summary: 删除用户
      tags:
      - 用户
    get:
      consumes:
      - application/json
      operationId: GetUserDetail
      parameters:
      - description: Bearer <jwt-token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal_handler_http.RspData'
            - properties:
                data:
                  $ref: '#/definitions/internal_handler_http.UserDetail'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
      summary: 获取用户详情
      tags:
      - 用户
    put:
      consumes:
      - application/json
      operationId: UpdateUser
      parameters:
      - description: Bearer <jwt-token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_handler_http.ReqUpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler_http.RspBase'
      summary: 更新用户
      tags:
      - 用户
swagger: "2.0"
