// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.0.0-EE
// Author: meta-egg
// Generated at: 2023-04-16 18:27
package domain

import (
	"meta-egg-layout/internal/common/resource"
	repo "meta-egg-layout/internal/repo"

	"github.com/google/wire"
)

// ProviderSet is domain providers.
var ProviderSet = wire.NewSet(
	NewDomainUsecase,
)

// 匿名用例
type DomainUsecase struct {
	Resource   *resource.Resource
	GenderRepo repo.GenderRepo
	UserRepo   repo.UserRepo
}

func NewDomainUsecase(
	rsrc *resource.Resource,
	genderRepo repo.GenderRepo,
	userRepo repo.UserRepo,

) *DomainUsecase {
	return &DomainUsecase{
		Resource:   rsrc,
		GenderRepo: genderRepo,
		UserRepo:   userRepo,
	}
}
