// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.0.4-EE
// Author: meta-egg
// Generated at: 2023-04-22 00:40
package handler

import (
	api "meta-egg-layout/api/meta_egg_layout"
	"meta-egg-layout/internal/common/resource"
	"meta-egg-layout/internal/domain"

	"github.com/google/wire"
)

// ProviderSet is grpc handler providers.
var ProviderSet = wire.NewSet(
	NewHandler,
)

var (
	DateLayout = "20060102"
	TimeLayout = "150405"
)

type Handler struct {
	api.UnimplementedMetaEggLayoutServer
	Resource      *resource.Resource
	DomainUsecase *domain.DomainUsecase

	// TODO: add your domain usecase
}

func NewHandler(
	rsrc *resource.Resource,
	domainUsecase *domain.DomainUsecase,

	// TODO: add your domain usecase
) *Handler {
	return &Handler{
		Resource:      rsrc,
		DomainUsecase: domainUsecase,

		// TODO: setup your domain usecase
	}
}
