// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.5.1-EE
// Author: meta-egg
// Generated at: 2023-05-22 16:28

package handler

import (
	"context"
	api "meta-egg-layout/api/meta_egg_layout"
	"meta-egg-layout/internal/common/constraint"

	"meta-egg-layout/internal/common/contexts"
)

// 获取用户详情
func (h *Handler) GetUserDetail(ctx context.Context, req *api.GetUserDetailRequest) (*api.GetUserDetailResponse, error) {
	log := contexts.GetLogger(ctx)
	mUser, err := h.BizService.GetUserByID(ctx, req.Id)
	if err != nil {
		log.WithError(err).Error("BizService.GetUserByID failed")
		return nil, err
	}
	return &api.GetUserDetailResponse{
		Id:        mUser.ID,
		Name:      mUser.Name,
		Gender:    mUser.Gender,
		Age:       uint32(mUser.Age),
		IsOnJob:   mUser.IsOnJob,
		CreatedBy: mUser.CreatedBy,
		CreatedAt: mUser.CreatedAt.Format(constraint.SecondTimeFormat),
		UpdatedBy: mUser.UpdatedBy,
		UpdatedAt: mUser.UpdatedAt.Format(constraint.SecondTimeFormat),
	}, nil
}
