// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.8.0
// Author: meta-egg
// Generated at: 2025-08-24 21:54

package biz

import (
	"meta-egg-layout/internal/common/resource"
	repo "meta-egg-layout/internal/repo"

	"github.com/google/wire"
)

// ProviderSet is biz providers.
var ProviderSet = wire.NewSet(
	NewBizService,
)

// 对数据实体的带业务规则的操作
type BizService struct {
	Resource    *resource.Resource
	UserRepo    repo.UserRepo
	GenderRepo  repo.GenderRepo
	UserTagRepo repo.UserTagRepo
	TagRepo     repo.TagRepo
}

func NewBizService(
	rsrc *resource.Resource,
	userRepo repo.UserRepo,
	genderRepo repo.GenderRepo,
	userTagRepo repo.UserTagRepo,
	tagRepo repo.TagRepo,
) *BizService {
	return &BizService{
		Resource:    rsrc,
		UserRepo:    userRepo,
		GenderRepo:  genderRepo,
		UserTagRepo: userTagRepo,
		TagRepo:     tagRepo,
	}
}
