// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.5.1-EE
// Author: meta-egg
// Generated at: 2023-05-22 16:28

package biz

import (
	"context"

	"errors"
	"meta-egg-layout/gen/model"
	"meta-egg-layout/internal/common/cerror"
	"meta-egg-layout/internal/common/contexts"

	"gorm.io/gorm"
)

func (u *BizService) GetGenderByID(ctx context.Context, id uint64) (*model.Gender, error) {
	log := contexts.GetLogger(ctx)
	mGender, err := u.GenderRepo.GetByID(ctx, id)
	if err != nil {
		log.WithError(err).Error("fail to get gender by id")
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, cerror.NotFound("gender not exist")
		} else {
			return nil, cerror.Internal()
		}
	}
	return mGender, nil
}
