// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v3.8.0
// Author: meta-egg
// Generated at: 2025-08-24 21:54

package biz

import (
	"context"

	"meta-egg-layout/gen/model"
	"meta-egg-layout/internal/common/cerror"
	"meta-egg-layout/internal/common/contexts"
	"meta-egg-layout/internal/repo/option"

	jgstr "github.com/Jinglever/go-string"
)

func (b *BizService) GetTagListByUserID(ctx context.Context, userId uint64, opt *TagListOption) ([]*TagListBO, int64, error) {
	log := contexts.GetLogger(ctx).
		WithField("userId", userId).
		WithField("opt", jgstr.JsonEncode(opt))

	// 转换biz层option为repo层option，调用BR表repo的方法
	relatedTags, total, err := b.UserTagRepo.GetTagListByUserID(ctx, userId, &option.TagListOption{
		Pagination: opt.Pagination,
		Order:      opt.Order,
		Select: []interface{}{
			model.ColTagID,
			model.ColTagName,
		},
	})
	if err != nil {
		log.WithError(err).Error("fail to get related tag list")
		return nil, 0, cerror.Internal(err.Error())
	}

	// 转换为ListBO，复用目标表的ToXxxListBO方法
	result, err := b.ToTagListBO(ctx, relatedTags)
	if err != nil {
		log.WithError(err).Error("fail to convert tag models to TagListBO")
		return nil, 0, cerror.Internal(err.Error())
	}
	return result, total, nil
}

func (b *BizService) GetUserListByTagID(ctx context.Context, tagId uint64, opt *UserListOption) ([]*UserListBO, int64, error) {
	log := contexts.GetLogger(ctx).
		WithField("tagId", tagId).
		WithField("opt", jgstr.JsonEncode(opt))

	// 转换biz层option为repo层option，调用BR表repo的方法
	relatedUsers, total, err := b.UserTagRepo.GetUserListByTagID(ctx, tagId, &option.UserListOption{
		Pagination: opt.Pagination,
		Order:      opt.Order,
		Filter: &option.UserFilterOption{
			Gender:  opt.Filter.Gender,
			IsOnJob: opt.Filter.IsOnJob,
		},
		Select: []interface{}{
			model.ColUserID,
			model.ColUserName,
			model.ColUserGender,
		},
	})
	if err != nil {
		log.WithError(err).Error("fail to get related user list")
		return nil, 0, cerror.Internal(err.Error())
	}

	// 转换为ListBO，复用目标表的ToXxxListBO方法
	result, err := b.ToUserListBO(ctx, relatedUsers)
	if err != nil {
		log.WithError(err).Error("fail to convert user models to UserListBO")
		return nil, 0, cerror.Internal(err.Error())
	}
	return result, total, nil
}

func (b *BizService) BindTagsToUser(ctx context.Context, userId uint64, tagIds []uint64) error {
	log := contexts.GetLogger(ctx).
		WithField("userId", userId).
		WithField("tagIds", tagIds)

	err := b.UserTagRepo.BindBatch(ctx, []uint64{userId}, tagIds)
	if err != nil {
		log.WithError(err).Error("fail to bind tags to user")
		return cerror.Internal(err.Error())
	}
	return nil
}

func (b *BizService) BindUsersToTag(ctx context.Context, tagId uint64, userIds []uint64) error {
	log := contexts.GetLogger(ctx).
		WithField("tagId", tagId).
		WithField("userIds", userIds)

	err := b.UserTagRepo.BindBatch(ctx, userIds, []uint64{tagId})
	if err != nil {
		log.WithError(err).Error("fail to bind users to tag")
		return cerror.Internal(err.Error())
	}
	return nil
}

func (b *BizService) UnbindTagsFromUser(ctx context.Context, userId uint64, tagIds []uint64) error {
	log := contexts.GetLogger(ctx).
		WithField("userId", userId).
		WithField("tagIds", tagIds)

	_, err := b.UserTagRepo.UnbindBatchFromUser(ctx, userId, tagIds)
	if err != nil {
		log.WithError(err).Error("fail to unbind tags from user")
		return cerror.Internal(err.Error())
	}
	return nil
}

func (b *BizService) UnbindUsersFromTag(ctx context.Context, tagId uint64, userIds []uint64) error {
	log := contexts.GetLogger(ctx).
		WithField("tagId", tagId).
		WithField("userIds", userIds)

	_, err := b.UserTagRepo.UnbindBatchFromTag(ctx, tagId, userIds)
	if err != nil {
		log.WithError(err).Error("fail to unbind users from tag")
		return cerror.Internal(err.Error())
	}
	return nil
}
