// Code generated by meta-egg. CAREFULLY EDIT.
// WILL NOT BE replace after re-generated, unless you confirm it!
// CAREFULLY EDIT.
// Version: v1.4.1-IE
// Author: meta-egg
// Generated at: 2023-05-18 18:11

package biz

import (
	"context"

	"errors"
	"meta-egg-layout/gen/model"
	"meta-egg-layout/internal/biz/option"
	"meta-egg-layout/internal/common/cerror"
	"meta-egg-layout/pkg/gormx"

	"gorm.io/gorm"

	log "github.com/sirupsen/logrus"
)

func (u *BizService) CreateUser(ctx context.Context, m *model.User) error {
	err := u.UserRepo.Create(ctx, m)
	if err != nil {
		log.Errorf("fail to create user: %v", err)
		return cerror.Internal()
	}
	return nil
}

func (u *BizService) GetUserByID(ctx context.Context, id uint64) (*model.User, error) {
	mUser, err := u.UserRepo.GetByID(ctx, id)
	if err != nil {
		log.Errorf("fail to get user by id: %v", err)
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, cerror.NotFound("user not exist")
		} else {
			return nil, cerror.Internal()
		}
	}
	return mUser, nil
}

type UserFilterOption struct {
	Gender *uint64
}

func (o *UserFilterOption) GetRepoOptions() []gormx.Option {
	ops := make([]gormx.Option, 0)
	if o.Gender != nil {
		ops = append(ops, gormx.Where(model.ColUserGender+" = ?", *o.Gender))
	}

	return ops
}

type UserListOption struct {
	Pagination *option.PaginationOption
	Filter     *UserFilterOption
	Order      *option.OrderOption
	Select     []interface{} // select columns, such as []interface{}{"id", "name"}
}

func (u *BizService) GetUserList(ctx context.Context, opt *UserListOption) ([]*model.User, int64, error) {
	ops := make([]gormx.Option, 0)
	if opt.Filter != nil {
		ops = append(ops, opt.Filter.GetRepoOptions()...)
	}
	if opt.Order != nil {
		validOrderby := []string{
			model.ColUserID,
		}
		ops = append(ops, opt.Order.GetRepoOptions(validOrderby)...)
	}
	total, err := u.UserRepo.Count(ctx, ops...)
	if err != nil {
		log.Errorf("fail to count user list: %v", err)
		return nil, 0, cerror.Internal()
	}
	if total == 0 {
		return make([]*model.User, 0), 0, nil
	}
	if opt.Pagination != nil {
		ops = append(ops, opt.Pagination.GetRepoOptions()...)
	}
	if len(opt.Select) > 0 {
		ops = append(ops, gormx.Select(opt.Select...))
	}
	mUserList, err := u.UserRepo.Gets(ctx, ops...)
	if err != nil {
		log.Errorf("fail to get user list: %v", err)
		return nil, 0, cerror.Internal()
	}
	return mUserList, total, nil
}

type UserSetOption struct {
	Name   *string
	Gender *uint64
	Age    *uint8
}

type UserUpdateOption struct {
	Set *UserSetOption
}

func (u *BizService) UpdateUserByID(ctx context.Context, id uint64, opt *UserUpdateOption) error {
	// assemble setCVs
	setCVs := make(map[string]interface{})
	if opt.Set != nil {
		if opt.Set.Name != nil {
			setCVs[model.ColUserName] = *opt.Set.Name
		}
		if opt.Set.Gender != nil {
			setCVs[model.ColUserGender] = *opt.Set.Gender
		}
		if opt.Set.Age != nil {
			setCVs[model.ColUserAge] = *opt.Set.Age
		}
	}

	_, err := u.UserRepo.UpdateByID(ctx, id, setCVs, nil)
	if err != nil {
		log.Errorf("fail to update user: %v", err)
		return cerror.Internal()
	}

	return nil
}

func (u *BizService) DeleteUserByID(ctx context.Context, id uint64) error {
	_, err := u.UserRepo.DeleteByID(ctx, id)
	if err != nil {
		log.Errorf("fail to delete user: %v", err)
		return cerror.Internal()
	}
	return nil
}
