// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"meta-egg-layout/internal/common/resource"
	"meta-egg-layout/internal/repo"
)

// Injectors from wire.go:

func WireBizService(rsrc *resource.Resource) *BizService {
	userRepo := repo.NewUserRepo(rsrc)
	genderRepo := repo.NewGenderRepo(rsrc)
	bizService := NewBizService(rsrc, userRepo, genderRepo)
	return bizService
}
